### ISSUE TITLE
problems importing .svp files

### ISSUE THREAD

**Issue by gummishoez** [sdercolin/utaformatix3#65]
i'm attempting to convert a .svp file to a .vsqx file but it doesn't seem to be working right; when i upload the file the screen says "processing..." and never actually loads. i tried to export the same synthv project as a .ust file to see if _that_ worked, and it worked just fine, so i'd assume it's the .svp format that's the problem here? i also tried to import other .svp files and got the same result.

**Comment by sdercolin** [comment]
@gummishoez 
Hello, thanks for your report. The svp import feature is working properly as we tested.
One possible cause is that, the svp project you are using contains pitch data and it may take time for the app to parse the project. Please try again with a "nearly-empty" svp project again.
The process time also depends on your computer's specification and browser environment (because it's processed locally by your browser).
If there are certain files that cannot be imported, please submit a feedback form with the file uploaded (you can find the button in the right-top bar of the app).

**Comment by gummishoez** [comment]
yeah, i understand then. i was just hoping to transfer as much pitch data as possible since i find editing in synthv to be much easier and have better results than in vocaloid. oh well, it is what it is. thank you for the help! ^^
